version: "3.8"
services:
  apache-php:
    image: php:8.2-apache
    container_name: apache-container
    ports:
      - "8080:80"  # Mappage des ports (localhost:8080)
    volumes:
      - ./html:/var/www/html
      - ./src:/var/www/src
      - ./css:/var/www/css
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    networks:
      - app-network
